baseURL = "/"
title = "Raspberry.wiki"
enableRobotsTXT = true
theme = "raspberry.wiki-site"
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

#  menu items
[[menu.main]]
    name = "Docs"
    weight = 2
    url = "docs/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

# Everything below this are Site Params

[params]
  author = "Finch"
  searchPlaceholder = "Search the docs ..."
  repo = "https://github.com/fringillidaes/raspberry.wiki-site/"

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  [params.logo]
    lightMode = "compose-light.svg"
    darkMode = "compose-light.svg"

  [params.source]
    name = "GitHub"
    icon = "github.svg"
    url = "https://github.com/fringillidaes/raspberry.wiki-site/"
